### ISSUE TITLE
Docker Hub?

### ISSUE THREAD

**Issue by MapGuy11** [evoactivity/hls-proxy-docker#5]
How Do You Feel With Putting The Image on Docker Hub? I am guessing this is the easiest way to message you.

**Comment by evoactivity** [comment]
I'd consider it for sure, we would probably want to get this into a slightly better state if we were to publish it there, for example switching to an alpine image instead of a full ubuntu image would reduce the container size a lot and using a proper CMD in the dockerfile, right now it just runs the shell script as the entrypoint, which I don't think is correct. The install should run as a RUN step after copying the script into the container and the CMD we run should be the hls-proxy server.

What do you think?

**Comment by MapGuy11** [comment]
Yes I will create a dev branch and recreate the dockerfile then look at it together. I think we can use node as I am pretty sure hls-proxy is a node application.
